title: Lora Bauer
logo: "Screenshot 2023-11-13 161202.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 2+ years of healthcare data experience in analytics, project management, and presentation, and a Master's degree in Health Informatics from the University of Denver. Previously at Johns Hopkins University, Columbia Community College, and The Denver Ophthalmology Center. 
  <br><br>
  Ranked in the top 10% of the graduate cohort at the University of Denver.
  <br><br>
  Currently a member of the Healthcare Data Analytics Association
  <br><br>
  <a href="https://www.linkedin.com/in/lorasbauer/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
